### ISSUE TITLE
update resolveKeys() to reflect new API

### ISSUE THREAD

**Issue by christiansmith** [anvilresearch/jose#17]
JWT `resolveKeys()` [instance method](https://github.com/anvilresearch/jose/blob/master/src/jose/JWT.js#L438-L477) still reflects the previous API (`v0.1.x`). We need to update this to accommodate the new API (`>=0.2.0`).

This method is used by [oidc-rs](https://github.com/anvilresearch/oidc-rs/blob/master/src/AuthenticatedRequest.js#L375).

**Comment by dmitrizagidulin** [comment]
👍 on this (this is used by oidc-rp and oidc-op as well)

**Comment by EternalDeiwos** [comment]
The functionality provided by `resolveKeys()` is being planned to be included in another library ([keycache](https://github.com/anvilresearch/keycache)). I'll reopen this issue on the keycache repo.
