### ISSUE TITLE
Update tests for JWK/JWA.importKeys()

### ISSUE THREAD

**Issue by dmitrizagidulin** [anvilresearch/jose#23]
The original test stubs for `JWK.importKeys()` expect the method to resolve with a JWK instance (and at the moment, it just resolves with a plain object with the relevant properties), and to have a `CryptoKey` property (which it doesn't seem to?).

Are those still correct expectations?

**Comment by dmitrizagidulin** [comment]
Also, there is a `TODO` question in the docstring of `JWK.importKeys()` -- "should this be on JWA?". 
I'm not sure if the question is asking whether JWT.importKeys() should delegate to JWA.importKeys(), or if client code should just call JWA.importKeys() directly.
Fwiw, my vote is - keep the situation as is, with JWT delegating to JWA, and remove that todo from the readme.

**Comment by christiansmith** [comment]
@dmitrizagidulin – could you take a peek at https://github.com/anvilresearch/jwk when you have a chance and see if these issues are addressed? If not, please file an issue there?

Thanks

**Comment by dmitrizagidulin** [comment]
Yep, will do!

**Comment by EternalDeiwos** [comment]
Given the recent conversation, I'll excuse this issue from my purging spree until @dmitrizagidulin gives me the go ahead to close it or submits a new issue on [jwk](https://github.com/anvilresearch/jwk).

**Comment by christiansmith** [comment]
Bwahahahaha!!! @dmitrizagidulin's first day at Trust tomorrow. Let's find things to pile up in his inbox :)
