### ISSUE TITLE
Fix support for JWT.encode() with alg: 'none'

### ISSUE THREAD

**Issue by dmitrizagidulin** [anvilresearch/jose#27]
Currently, we have entries like `supportedAlgorithms.define('none', 'sign', {})` in the algorithms registry, so when you try `JWT.encode()` where `header: { alg: 'none' }`, it throws a 'that's not a function' error.

**Comment by christiansmith** [comment]
see #33

**Comment by EternalDeiwos** [comment]
This is handled in anvilresearch/jwa#4. Closing the issue.
